# LibNT5
# Provides replacements for missing functions to allow v141_xp compiled
# binaries to run on Windows 2000 and XP RTM - SP2.

import("//build/config/precompiled_header.gni")
import("//build/config/static_shared.gni")
import("//build/config/win/manifest.gni")
import("//build/config/win/target_version.gni")

# Build everything, dependants should depend on this target
# or one of the "libnt5_*" targets (usually "libnt5_static"). 
group("libnt5_all") {
  testonly = true
  public_deps = [
    ":libnt5",
    ":libnt5_tests",
  ]
}

# Build everything excluding tests
group("libnt5") {
  public_deps = [
    ":libnt5_headers",
    ":libnt5_libs",
  ]
}

# Build just libraries
group("libnt5_libs") {
  deps = [
    ":copy_libnt5_libs",
  ]
  public_deps = [
    ":libnt5_static",
    #":libnt5_shared",
  ]
}

# Unit tests and test program(s)
group("libnt5_tests") {
  testonly = true
  public_deps = [
    ":libnt5_test",
  ]
}

# Small test program to make sure lib makes programs that run on Win 2K
executable("libnt5_test") {
  testonly = true
  configs -= [
    "//build/config/win:nominmax",
    "//build/config/win:console",
  ]

  configs += [
    "//build/config/win:lean_and_mean",
    "//build/config/win:windowed",
    ":libnt5_public_config",
  ]

  sources = [
    "tests\libnt5_test.cc",
  ]

  public_deps = [
    ":libnt5",
  ]
}

# Headers for consumers of the library
source_set("libnt5_headers") {
  configs -= [ "//build/config/win:nominmax", ]
  configs -= [ "//build/config/win:default_libs" ]
  configs += [
    "//build/config/win:lean_and_mean",
    "//build/config:no_default_lib",
  ]

  sources = [
    "src/libnt5.h",
    "src/libnt5_dll.h",
  ]
}

# Originally called EnlyzeWinCompatLib
static_library("libnt5_static") {
  configs -= [ "//build/config/win:nominmax", ]
  configs -= [ "//build/config/win:default_libs" ]
  configs += [
    "//build/config/win:lean_and_mean",
    "//build/config:no_default_lib",
    ":libnt5_private_config",
  ]

  sources = [
    "src/targetver.h",
    "src/libnt5.h",
    "src/libnt5_internal.h",
    "src/version.h",
  ]
  sources += [
    "src/winnt_50.cc",
    "src/winnt_51.cc",
    "src/winnt_51_sp2.cc",
  ]
  sources += [
    "src/winnt_50_forwarders.asm",
    "src/winnt_51_forwarders.asm",
    "src/winnt_51_sp2_forwarders.asm",
  ]
  output_name = "libnt5"
}

# DLL version
shared_library("libnt5_shared") {
  configs -= [ "//build/config/win:nominmax", ]
  configs -= [ "//build/config/win:default_libs" ]
  configs += [
    "//build/config/win:lean_and_mean",
    "//build/config:no_default_lib",
    ":libnt5_private_config",
  ]

  sources = [
    "src/libnt5_dll.h",
  ]
  output_name = "libnt5"
}

# Copy built .libs to build output dir
copy("copy_libnt5_libs") {
  sources = [
    "$root_out_dir/obj/src/libnt5/libnt5.lib",
  ]
  outputs = [
    "$root_out_dir/libnt5.lib",
  ]
  public_deps = [
    ":libnt5_static",
    #":libnt5_shared",
  ]
}

# Compiler config for libnt5 itself
config("libnt5_private_config") {
  # Don't use precompiled headers
  cflags = [ "/Y-", ]
  ldflags = []
  libs = []
}

# Compiler config for dependants/consumers to link the library in properly for Win 2k
config("libnt5_public_config") {
  cflags = []
  ldflags = []
  libs = []

  ldflags += [
    "/DEFAULTLIB:libnt5.lib",
  ]
  libs += [
    "libnt5.lib",
  ]
}
